import type { ComponentDef } from '@sim/contracts';

export const L298N: ComponentDef = {
  slug: 'l298n',
  displayName: 'L298N 电机驱动',
  category: 'actuator',
  icon: 'L298',
  version: '1.0.0',
  description:
    '双 H 桥直流电机驱动。控制侧接 GPIO（IN1–IN4 / ENA / ENB），输出侧接电机（OUT1–OUT2），+12V 接独立电源，必须与开发板共地。',
  ports: [
    {
      id: 'ENA',
      name: 'ENA（调速）',
      role: 'signal',
      direction: 'in',
      voltageDomain: '3V3',
      required: true,
      protocols: ['PWM'],
      note: '电机 A 使能端：接 PWM 可调速，接高电平则全速',
    },
    {
      id: 'IN1',
      name: 'IN1',
      role: 'signal',
      direction: 'in',
      voltageDomain: '3V3',
      required: true,
      protocols: ['GPIO'],
      note: '电机 A 方向控制（IN1/IN2 一高一低决定正反转）',
    },
    {
      id: 'IN2',
      name: 'IN2',
      role: 'signal',
      direction: 'in',
      voltageDomain: '3V3',
      required: true,
      protocols: ['GPIO'],
      note: '电机 A 方向控制',
    },
    {
      id: '+12V',
      name: '+12V',
      role: 'power',
      direction: 'in',
      voltageDomain: 'VIN',
      required: true,
      note: '电机电源输入（7–12V），必须使用独立电源而非开发板引脚',
    },
    {
      id: 'GND',
      name: 'GND',
      role: 'ground',
      direction: 'in',
      voltageDomain: 'GND',
      required: true,
      note: '必须与开发板 GND 相连（共地），否则控制信号没有参考电平',
    },
    {
      id: 'OUT1',
      name: 'OUT1',
      role: 'signal',
      direction: 'out',
      voltageDomain: 'VIN',
      required: false,
      note: '接电机 A 一端（本平台暂不支持"器件直连"，为接线示意端口）',
    },
    {
      id: 'OUT2',
      name: 'OUT2',
      role: 'signal',
      direction: 'out',
      voltageDomain: 'VIN',
      required: false,
      note: '接电机 A 另一端（极性反接则电机反转）',
    },
  ],
  protocols: ['PWM'],
  requirements: ['external-power'],
  portOptions: [
    {
      key: 'externalSupply',
      label: '已使用独立电源（与开发板共地）',
      kind: 'toggle',
      defaultValue: false,
      satisfies: 'external-power',
    },
  ],
};
